### ISSUE TITLE
Чистые исключения

### ISSUE THREAD

**Issue by evgeny-osipenko** [KateBu/bot-1.3#12]
Исключения бросаются через `pure . throw`:
https://github.com/KateBu/bot-1.3/blob/fad066a240db6b7f0a17b68d7897e4b94faee7b5/src/Exceptions/Functions.hs#L21
Так делать не следует - если результат проигнорируется, то исключения не будет:
```hs
do
  throwInitConfigExcept -- результат не использован - эффекта ноль
  putStrLn "oops" -- печатает

do
  x <- throwInitConfigExcept -- ошибка спрятана внутри x
  putStrLn "oops" -- печатает
  print (x :: Int) -- ошибка из x поднимается наружу
```
Как правило, когда требуется поднять исключение в монаде - это делается с помощью функции, предназначенной именно для этой монады.
Если используется только `IO` - то в нём вызывается функция `throwIO`, которая гарантированно поднимет исключение точно по своему месту в монаде.
Если используются стаки поверх `IO` - то можно воспользоваться `MonadIO` и прописать `liftIO . throwIO`
Если нужно поднимать произвольные исключения и в других монадах - можно прописать свой собственный тайпкласс `MonadThrow` с соответствующими реализациями - например, через `throwIO` для ио-стеков и через `throwError` для чистого кода, с использованием `ExceptT`.

**Comment by KateBu** [comment]
сделала MonadThrow тайпкласс, который в ИО монаде бросает исключение через throwIO и для тестов сделала экземпляр для Maybe, который возвращает Nothing. Не уверена, что все в этом виде и останется - на данный момент у меня не были предусмотрены другие варианты обработки исключений кроме как завершение программы, поэтому не использовала ExceptT.

**Comment by KateBu** [comment]
Все исключения теперь кидаются через функцию throwBotExcept, которая прописана в тайпклассе BotEx.MonadThrow
