### ISSUE TITLE
OverloadedStrings

### ISSUE THREAD

**Issue by evgeny-osipenko** [KateBu/bot-1.3#13]
https://github.com/KateBu/bot-1.3/blob/a59c45dc1ed3645ef718ebe25cb8e4b37ba34c5f/src/Environment/SetEnvironment.hs#L30
и подобные можно записать как
```hs
    botT <- Configurator.lookup conf "bot.botType" :: IO (Maybe T.Text) 
```
[OverloadedStrings](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/overloaded_strings.html) - достаточно распространённое расширение, так что его использование совсем не осуждается, а иногда даже приветствуется. :)

**Comment by KateBu** [comment]
done!
