### ISSUE TITLE
Управление соединениями БД

### ISSUE THREAD

**Issue by evgeny-osipenko** [KateBu/bot-1.3#14]
Насколько я помню, сохранять настройки пользователей на диске было не обязательно, но раз уж взялись за это, к тому же ещё и с базой данных - то тогда сразу обращу внимание на возможные проблемы.

https://github.com/KateBu/bot-1.3/blob/92d4612d96153e38ee4d4a8df2760af9cbe0b234/src/Services/DB/Database/Functions.hs#L33-L37

Как видно из этой функции - при каждой операции, программа создаёт новое соединение БД, и затем оставляет его на совесть сборщика мусора.

Считается, что соединения БД - это "ценный" ресурс, так же как открытые файлы, сетевые соединения, удерживаемые блокировки и прочие - а это значит, что их лучше освобождать как можно раньше; и освобождение следует производить даже в случае возникновения исключений.

Конкретно в случае БД, это делается примерно таким образом:

```hs
withConnection :: P.ConnectInfo -> IO a -> IO a
withConnection connInfo body = do
  Ex.bracket init release body
  where
    init = P.connect connInfo
    release conn = P.close conn

find :: Config.Config -> Logger.Logger IO -> Int -> IO (Maybe Int)
find bType logger userId = do
  Ex.handle BotEx.throwSQLException $ do
    withConnection connectInfo $ \conn -> do
      resp <- P.query_ conn (findUserQuery bType userId) `Ex.catches` BotEx.dbErrorsHandlers
      checkFindResponse logger resp
```

[bracket](https://hackage.haskell.org/package/base-4.14.1.0/docs/Control-Exception.html#v:bracket) также отличается тем, что маскирует асинхронные исключения - в принципе, в любой момент в программе, мы можем прервать её, например, нажатием Ctrl+C - и это создаст исключение в том месте, которое сейчас исполняется (хотя в самом коде никаких исключений может и не быть). Без маскировки, это может произойти и в любой момент внутри `connect` и `close`, поэтому их следует вызывать в качестве аргументов `bracket` - он маскирует исключения таким образом, что инициализация и финализация обязательно выполнятся до конца (если только сами не поднимут исключение через вызов throwIO), и если взятие ресурса дошло до конца и не сломалось - то и освобождение будет обязательно исполнено, независимо от того, каким образом произойдёт выход - через обычный возврат значения, через throwIO или через асинхронное исключение.

Этот паттерн можно применить и к хендлу - функцию `new` спрятать в приватной части модуля, а наружу экспортировать функцию такого вида:

```hs
withDbHandle :: Env.Environment IO -> (Handle IO -> IO a) -> IO a
withDbHandle env = bracket (new env) release
```

Тогда вместо того, чтобы создавать по новому соединению на каждый запрос, можно будет хранить одно постоянное соединение, инициализировать его в `new` и закрывать в `release`.

**Comment by KateBu** [comment]
у меня раньше в мапе все хранилось.. рекомендовали использовать бд (пусть даже из одной таблицы), чтобы получить представление , как с ней работать. 
Т.о. правильно ли я понимаю, что
- если я создаю подключения для каждого запроса, я использую функцию с брекетом, которая создает подключение, закрывает его, и между этими событиями в случае удачного открытия выполняет запрос. 
- если я использую одно подключение, которое создаю при создании ДБхэндла (также функцией с брекетом), я передаю уже готовое подключение в функции. При этом если возникнет какая-то ошибка (являющаяся инстансом Exception) во время существования хэндла,  то withDbHandle отработает освобождение ресурсов и тоже кинет эту ошибку при завершении. При этом выполнение самих функций я могу также оформить брекетами, которые, будут кидать свои ошибки на более низком уровне.

То есть получается, что лучше использовать второй вариант?

**Comment by KateBu** [comment]
- вынесла строку подключения к бд в кофиг-файл
- сделала установку и закрытие соединения при каждом обращении к БД.

**Comment by KateBu** [comment]
Что я в итоге сделала: 
- все функции для работы с БД вызываю через withDBConnection (внутри которой в брекетах осуществляется создание соединения, выполнение действий, закрытие соединения)
- для БД и АПИ сделала функции new, close, withHandle, соответственно каждая функция из хэндлов теперь вызывается через withHandle в брекетах.
- сделала тайпкласс Services, в котором прописала каждую функцию из обоих хэндлов 
```
class (Monad m) => Services m where
  getUpdates :: Env.Environment m -> m [PureStructs.PureMessage]
  sendMessage :: Env.Environment m -> PureStructs.PureMessage -> m (Env.Environment m)
  findUser :: Env.Environment m -> PureStructs.ChatID -> m (Maybe Env.RepeatNumber)
  addUser :: Env.Environment m -> PureStructs.ChatID -> Env.RepeatNumber -> m ()
  updateUser :: Env.Environment m -> PureStructs.ChatID -> Env.RepeatNumber -> m ()
```
- сделала инстанс для ИО
- в тестах сделала инстанс для Maybe

**Comment by evgeny-osipenko** [comment]
В принципе, такой подход нормальный.
Для общего развития - то, что тайпкласс `Services m` тут делает, иногда называется "зависимостью" (dependency); а когда код, который используется эту зависимость, получает её снаружи - "инверсия зависимости" (dependency inversion).
Конкретно в этом случае можно вместо того, чтобы вручную передавать `Environment`, закрепить его в монаде:
```haskell
class (Monad m) => ServiceMonad m where
  getEnvironment :: m (Env.Environment m)
  getUpdates :: m [PureStructs.PureMessage]
  sendMessage :: PureStructs.PureMessage -> m ()
  findUser :: PureStructs.ChatID -> m (Maybe Env.RepeatNumber)
  addUser :: PureStructs.ChatID -> Env.RepeatNumber -> m ()
  updateUser :: PureStructs.ChatID -> Env.RepeatNumber -> m ()
instance ServiceMonad (StateT Env.Environment IO) where
  ...
instance ServiceMonad (StateT Env.Environment (State [ActionLog])) where
  ...
```
Такой подход носит название "final tagless encoding".
Кроме него, есть handle pattern:
```haskell
data ServiceHandle m = ServiceHandle
  { getEnvironment :: m (Env.Environment m)
  , getUpdates :: m [PureStructs.PureMessage]
  , sendMessage :: PureStructs.PureMessage -> m ()
  , findUser :: PureStructs.ChatID -> m (Maybe Env.RepeatNumber)
  , addUser :: PureStructs.ChatID -> Env.RepeatNumber -> m ()
  , updateUser :: PureStructs.ChatID -> Env.RepeatNumber -> m ()
  }
makeMainServiceHandle :: ServiceHandle (StateT Env.Environment IO)
makeMainServiceHandle = ServiceHandle
  { ...
  }
-- можно совместить с взятием ресусов и вместо этого дать
withMainServiceHandle :: (ServiceHandle (StateT Env.Environment IO) -> StateT Env.Environment IO a) -> IO a

makeMockServiceHandle :: ServiceHandle (StateT Env.Environment (State [ActionLog]))
makeMockServiceHandle = ServiceHandle
  { ...
  }
```
Наконец, есть free monad:
```haskell
data ServiceAction m result where
  GetEnvironment :: ServiceAction m (Env.Environment m)
  GetUpdates :: ServiceAction m [PureStructs.PureMessage]
  SendMessage :: PureStructs.PureMessage -> ServiceAction m ()
  FindUser :: PureStructs.ChatID -> ServiceAction m (Maybe Env.RepeatNumber)
  AddUser :: PureStructs.ChatID -> Env.RepeatNumber -> ServiceAction m ()
  UpdateUser :: PureStructs.ChatID -> Env.RepeatNumber -> ServiceAction m ()

newtype ServiceT m a = ServiceT
  { runServiceT ::
      forall b.
      (forall result. ServiceAction m result -> (result -> b) -> b) -> (a -> b) -> b
  }

instance Monad (ServiceT m) where
  return x = ServiceT $ \exec next -> next x
  mx >>= sel = ServiceT $ \exec next ->
    runServiceT mx exec $ \x ->
      runServiceT (sel x) exec next

liftServiceAction :: ServiceAction m result -> ServiceT m result
liftServiceAction action = ServiceT $ \exec next -> exec action next

...
sendMessage :: PureStructs.PureMessage -> ServiceT m ()
sendMessage message = liftServiceAction $ SendMessage message
...

interpretServiceTMain :: ServiceT IO a -> IO a
interpretServiceTMain mx = runServiceT exec return `execStateT` initialEnvironment
  where
  exec :: ServiceAction m result -> (result -> StateT Env.Environment IO a) -> StateT Env.Environment IO a
  ...
  exec (SendMessage message) next = do
    r <- doSendMessageInIO message
    next r
  ...

interpretServiceTMock :: ServiceT (StateT [ActionLog]) a -> StateT [ActionLog] a
interpretServiceTMock mx = runServiceT exec return `execStateT` initialEnvironment
  where
  exec ::
    ServiceAction m result ->
    (result -> StateT Env.Environment (State [ActionLog]) a) ->
    StateT Env.Environment (State [ActionLog]) a
  ...
  exec (SendMessage message) next = do
    lift $ state (SendMessageAction message :)
    next ()
  ...
```
