### ISSUE TITLE
Параметры соединения БД

### ISSUE THREAD

**Issue by evgeny-osipenko** [KateBu/bot-1.3#15]
Практически во всех приложениях, где используются базы данных, параметры соединения - логин, пароль, адрес - задаются в файле конфигурации и могут меняться без перекомпиляции приложения.

Поскольку у бота уже есть файл конфигурации - то лучше параметры БД тоже считывать из него.

Конкретно в случае PostgreSQL, кстати говоря, параметры соединения можно свести в одну текстовую строку, называемую "[connection string](https://www.postgresql.org/docs/13/libpq-connect.html#LIBPQ-CONNSTRING)" - прочитать её из конфига как произвольную текстовую строку, передать в [connectPostgreSQL](https://hackage.haskell.org/package/postgresql-simple-0.6.4/docs/Database-PostgreSQL-Simple.html#v:connectPostgreSQL) без изменений, и если в ней возникнет какая-то ошибка - поймать исключение от библиотеки и вывести сообщение об ошибке.

Текущим настройкам соответствует строка `host='localhost' port='5432' user='bot' password='bot13' dbname='users'` - можно прописать её в шаблоне конфига как значение по умолчанию.

**Comment by KateBu** [comment]
вынесла в конфиг-файл строку с настройками соединения
