### ISSUE TITLE
Использовать newtype вместо data

### ISSUE THREAD

**Issue by DonDokidon** [KateBu/bot-1.3#16]
https://github.com/KateBu/bot-1.3/blob/1b7296fd3b7b20d6bf503af1fde9bf6113982d28/src/API/Telegram/Structs/Attachments/Animation.hs#L8-L11
Типы с одним конструктором и одним аргументом должны создаваться через newtype

**Comment by KateBu** [comment]
исправила, в остальных местах, где одно поле, тоже исправила
