### ISSUE TITLE
Длинные выражения в теле функции

### ISSUE THREAD

**Issue by DonDokidon** [KateBu/bot-1.3#17]
https://github.com/KateBu/bot-1.3/blob/1b7296fd3b7b20d6bf503af1fde9bf6113982d28/src/API/Telegram/Cleaners/Attachments/MbAnimation.hs#L15-L30
Выражение как на 28-29 стоит выносить в where. Вообще если выражение занимает больше одной строчки кода, то скорее всего его стоит вынести в where, а если и там оно слишком длинное, то мб стоит разбить на функции поменьше.

**Comment by KateBu** [comment]
вынесла в where выражение, по проекту тоже прошла, исправила такие случаи
