### ISSUE TITLE
Мелкие ошибки

### ISSUE THREAD

**Issue by DonDokidon** [KateBu/bot-1.3#18]
Пропусти весь код через hlint и исправь все на то что он там тебе предложит. Ну и в дальнейшем после изменений чекай, чтобы новых ошибок не появилось

**Comment by KateBu** [comment]
да, исправила

**Comment by DonDokidon** [comment]
Точно? Мой еще 12 ошибок выдает. Все перечислять не буду, но https://github.com/KateBu/bot-1.3/blob/24b7b6996dc5eed977feed6ddabcc76cb15c4dec/src/API/VK/Cleaners/ToPureMessages.hs#L30-L33 и https://github.com/KateBu/bot-1.3/blob/24b7b6996dc5eed977feed6ddabcc76cb15c4dec/src/Environment/Logger/Structs.hs#L21-L23 например

**Comment by KateBu** [comment]
я неправильно пользовалась хлинтом. Теперь исправила.
