### ISSUE TITLE
Непонятные сокращения

### ISSUE THREAD

**Issue by DonDokidon** [KateBu/bot-1.3#19]
https://github.com/KateBu/bot-1.3/blob/24b7b6996dc5eed977feed6ddabcc76cb15c4dec/src/TextMessages/LoggerMessages/Telegram.hs#L17-L18
Все функции должны называться так, чтобы четко описывать что они делают, используя только понятные сокращения.
https://github.com/KateBu/bot-1.3/blob/24b7b6996dc5eed977feed6ddabcc76cb15c4dec/src/API/Wrapper/GetUpdate.hs#L29-L31
Даже если они не экспортируются и даже если они находятся в where.
https://github.com/KateBu/bot-1.3/blob/24b7b6996dc5eed977feed6ddabcc76cb15c4dec/src/API/Bot.hs#L16
То же самое касается переменных. Можно использовать общепринятые сокращения вроде txt, msg, mb, но handler или updateId лучше писать полностью, чтобы сразу было понятно что это, не смотря в типы или куда-либо еще. 
PS. Вангуя появление telegramDecodeBSSuccessMsg, на месте использования можешь в where вынести
`logMsg = telegramDecodeBSSuccessMsg`

**Comment by KateBu** [comment]
env считается общепринятым сокращением?

**Comment by KateBu** [comment]
исправила имена функций/переменных/конструкторов

**Comment by DonDokidon** [comment]
Да, env норм. Если хоть где-то видела такое сокращение, то скорее всего оно нормальное
