### ISSUE TITLE
Модули и функции в них

### ISSUE THREAD

**Issue by DonDokidon** [KateBu/bot-1.3#20]
Я все еще не до конца могу понимать твой код по причинам, описанным ниже, и потому, что наши подходы к разделению на модули сильно различаются (в моем боте было около 17 модулей лол), поэтому в данном ишью отстаивание своей позиции и исправление меня более чем приветствуется.
1) Каждый модуль должен экспортировать что-то полезное для всего остального приложения. Т.е ты должна свести к минимуму экспортирование функций, которые могут быть применены только в рамках задач конкретного модуля, а вне его они никогда не понадобятся. Иногда такие функции приходится экспортировать, чтобы не копипастить их всюду. Тогда эти функции помещают в модуль `Internals`, именно поэтому его напрямую обычно не экспортируют.
2) Функции должны содержать в названии действия, которые они совершают (get, build, init ...). Тут  трудно вывести универсальное правило, т.к есть всякие `maybe` и конструкторы типов, так что просто просмотри название своих функций
и подумай, не нужно ли тут вставить действие?
3) В идеале писать экспорты руками, чтобы чего лишнего не экспортировать.
4) Обычно модули называются существительными и содержат функции, которые как-то связаны с этим существительным своим действием, поэтому `MakePureMessage` обычно там не увидишь.
5) Не стоит названием функции описывать работу над типами (офк если это не является прямым назначением функции, скорее всего функции cast). `telByteStringToPureMessageList` - слишком длинно и обезличено, мб что-то вроде `decodePureMessages`?)

____________________________________________________________________________________________________________________
`API.Telegram.Cleaners.GetParams` - Модуль назван неверно по причине (4) и ты не гетаешь параметры, ты их скорее билдишь. Этот модуль не используется нигде, кроме модуля с построением аттачментов, так что ему бы быть где-нибудь в Internals вообще. Ну build в их название я бы добавил. Модуль экспортирует локальную функцию
`API.Telegram.Cleaners.Keyboard` - Как это относится к Cleaners?
`API.Telegram.Cleaners.MakeMbParams` - функции уровня where и ты их не так часто используешь, чтобы для них отдельный модуль создавать. Опять же не понимаю, как это к Cleaners относится.
`API.Telegram.Cleaners.MakePureMessage` - содержит действие в названии модуля и экспортирует локальные функции. Зачем приписка tel в `telUpdateToPureMessage`? Делай qualified импорт, если они с VK встречаются, а приписок не надо.
`API.Telegram.Cleaners.MbMsgType` - экспортирует онли модули из Attachments, при этом сам называется MbMsgType. Уравняй их названия.
`API.Telegram.Data` - по причине того, что функции названы без нужных глаголов, но при этом содержат их в качестве существительных, думается, что ты апдейтишь HostPath, хотя на деле ты его билдишь. И я не уверен в названии модуля, мб Routes/URLs было бы информативнее, как думаешь?

Думаю пока что этого хватит,с остальными модулями попробуй сама разобраться. Можешь полазить по Hoogle, чтобы посмотреть как люди модули называют

**Comment by KateBu** [comment]
привет, я поняла мысль, думаю, тут еще проблема в структуре - проект рос стихийно и нынешняя структура не соответствует итогу логически. Я начала переделывать, разбивая на логические части по ходу работы программы - сделала на данный момент окружение - модули и папки, функции пока не трогала. 
Была мысль прописать ход работы программы в ридми, но если в этом нет необходимости, то лучше не буду.

**Comment by KateBu** [comment]
в общем, я привела все в читабельный вид, поправила структуру проекта, переименовала модули и функции. Осталось внести исправления в ридми файл

upd: иперепроверить экспорты

**Comment by KateBu** [comment]
- доделала структуру/переименование модулей и функций
- переписала ридми
- по поводу экспортов - инкапсулировала внутренние функции в модулях, явно прописав экспорты (не знаю, насколько это правильно), также получились иерархические экспорты (например, модуль Environment.Config.Exports импортируется в Environment.Exports, но не в полном объеме) - тоже не знаю, насколько это правильный подход, но , пожалуй, логично, что используемые при инициализации Environment функции из Environment.Config.Exports не экспортируются дальше туда, где они не нужны. По поводу логической части - там не получилось ничего инкапсулировать, т.к. по заданию надо на все функции из логики писать юнит-тесты, то есть они должны быть доступны извне.

**Comment by DonDokidon** [comment]
Сори что редко просматриваю, завал на проекте :) 
Повторюсь, не нужно делать приписки tel/telegram/etc в именах структур, конструкторов и функций. По большому проекту может встречаться несколько разных типов Person, не будешь же ты каждому приписку делать, чтобы уточнять откуда он. Делай qualified импорт, тогда твое TelUpdateResult заменится на Tel.UpdateResult.

>  по заданию надо на все функции из логики писать юнит-тесты

Никто не говорил тестировать вообще ВСЕ функции :) Локальные функции косвенно тестируются через те места, где они используются. Т.е достаточно тестировать только экспортируемые функции. 

___________________________________________________________________________________________________
`API.VK.Functions.Params.Fwd` и другие - Сокращения в функциях еще ладно, но модули настолько сокращать не надо (я про Forward, Params сойдет)
`API.VK.Functions.MsgTypes.TextMsg` - Имя MsgTypes подразумевает, что внутри хранятся MessageType, думаю уточнять это в TextMsg не требуется.
`Logic.Structs.PureMessage` - Почти все использования этих конструкторов приходятся на модули из API, при этом эти структуры находятся в Logic почему-то. Мне кажется модули из API должны содержать все необходимые функции/типы для общения с API телеги и вк, а в логике ты только экспортируешь их и используешь в нужном порядке, чтобы добиться нужного поведения. Вот тут вроде похожая ситуация - `Wrapper.Structs`. Вообще я хз насколько это правильно, но я не люблю циклические зависимости между модулями (тут в чуть более глобальном смысле, а не просто 2 hs файла друг друга вызывающие). Имхо должен быть какой-то главный модуль, который предоставляет другим свои типы и функции, а другие уже вокруг этого свою логику строят. И вот тут именно та цикличность, о которой я говорю - API экспортирует модуль Wrapper'a для построения HostPath, а потом Wrapper экспортирует модуль из API, чтобы эти HostPath получить. Выглядит странно.
`API.Telegram.Functions.Params` -  все еще экспортирует локальную функцию и не все функции имеют действие в названии.

**Comment by KateBu** [comment]
- по сокращениям и названиям исправила
- убрала циклические импорты модулей, соответственно, поменялась структура. Получилось, что все построения урлов для вк и телеграма ушли во wrapper, это нормально?
- сделала экспорт одной функции из логики

... тесты еще нужно переписывать, как и ридми

**Comment by KateBu** [comment]
доделала тесты и ридми

**Comment by DonDokidon** [comment]
https://github.com/KateBu/bot-1.3/blob/4acb764b078304de8da37625f734a2de1240b988/src/API/Telegram/Structs/Chat.hs#L8-L11
филды это по сути тоже функции, поэтому должны писаться в одном стиле с остальными функциями, т.е в camelCase. Тебе это не нужно, оно в линзах вроде используется, но если очень хочется выделить филды, можешь в начале _ приписать (_myField)
https://github.com/KateBu/bot-1.3/blob/4acb764b078304de8da37625f734a2de1240b988/src/Environment/Initialization.hs#L52-L58 
В идеале функции/переменные со штрихом не юзать, т.к их слишком просто перепутать с оными без штриха.
https://github.com/KateBu/bot-1.3/blob/4acb764b078304de8da37625f734a2de1240b988/src/API/VK/Functions/MsgTypes/Callback.hs#L21-L28
А если у тебя границы от 1 до 100 будешь 100 функций создавать? :) сделай из этого одну функцию. Можешь обрезать начало команды и просто maybeRead число. Кроме того вроде у тебя там при ошибке число повторов на 5 ставится. Логичнее было бы сбрасывать на 1? И еще как я говорил выше, сокращения в именах модулей не нужны (MsgTypes) (ну если это не аббревиатура)
https://github.com/KateBu/bot-1.3/blob/4acb764b078304de8da37625f734a2de1240b988/src/API/Telegram/Structs/MessageInfo.hs#L38-L54
Сейчас уже можешь не исправлять, но не делай универсальные типы данных и функции путем делания их инпутов Maybe. У нас сейчас проект, где все филды Maybe... Поверь мне, ты не хочешь работать над таким проектом... В данном случае видео/фото/etc исключают друг друга, поэтому можно было бы создать для них единый тип Content, он тоже был бы Maybe, но по крайней мере тебе не пришлось бы проходить по куче Maybe, чтобы понять чем он является, это делалось бы обычным case of

**Comment by KateBu** [comment]
> филды это по сути тоже функции, поэтому должны писаться в одном стиле с остальными функциями, т.е в camelCase. Тебе это не нужно, оно в линзах вроде используется, но если очень хочется выделить филды, можешь в начале _ приписать (_myField)

Тут не в кэмэлКейсе не потому что это филды, а потому что парсятся из джейсона местами автоматически. Да, надо было все однотипно сделать, с учетом того, что deriving Generic всего в паре-тройке мест..

> В идеале функции/переменные со штрихом не юзать, т.к их слишком просто перепутать с оными без штриха.

ок, поняла

> А если у тебя границы от 1 до 100 будешь 100 функций создавать? :) сделай из этого одну функцию. Можешь обрезать начало команды и просто maybeRead число. 

Переписала в одну функцию. 

> Кроме того вроде у тебя там при ошибке число повторов на 5 ставится. Логичнее было бы сбрасывать на 1? 

исправила

> И еще как я говорил выше, сокращения в именах модулей не нужны (MsgTypes) (ну если это не аббревиатур

исправила

> Сейчас уже можешь не исправлять, но не делай универсальные типы данных и функции путем делания их инпутов Maybe. У нас сейчас проект, где все филды Maybe... Поверь мне, ты не хочешь работать над таким проектом... В данном случае видео/фото/etc исключают друг друга, поэтому можно было бы создать для них единый тип Content, он тоже был бы Maybe, но по крайней мере тебе не пришлось бы проходить по куче Maybe, чтобы понять чем он является, это делалось бы обычным case of

поняла
