### ISSUE TITLE
ADT

### ISSUE THREAD

**Issue by Gmihtt** [KateBu/bot-1.3#5]
https://github.com/KateBu/bot-1.3/blob/d272ccdaa107ac53509f89d83e0ca3c17c3c1a9c/src/Config/Config.hs#L30
Лучше сделать эти типы раздельно, к примеру:
```
data BotTypes = BotTg Telegram | BotVK VK
data Telegram = ...
data VK = ...
```

**Comment by KateBu** [comment]
сделала, так удобнее получилось, спасибо
