### ISSUE TITLE
Именования в тайп сигнатурах

### ISSUE THREAD

**Issue by DonDokidon** [KateBu/bot-1.3#6]
Привет, тоже периодически буду ревьювить твой проект :)
https://github.com/KateBu/bot-1.3/blob/04be57027cfa47804428e1bd90c163b4fcb8b70b/src/Environment/InitEnvironment/InitEnvironment.hs#L11-L16

Хорошей практикой является давать базовым типам имена, которые точнее отражают суть переданных или возвращаемых значений. Можно делать это просто через `type` но чаще всего предпочтительнее оборачивать в `newtype`. Так ты даже из кода будешь видеть, что вот в эту функцию тебе (условно) нужно передать VKBotKey, и строчки `myFunc (VKBotKey telegramBotKey)` ты скорее всего уже не напишешь, да и другому человеку будет намного проще понимать твой код. Офк не нужно этого делать там, где и так все ясно.

P.S.  Можешь оспорить любой из моих ишью, если считаешь, что я не прав :)

**Comment by KateBu** [comment]
привет, 
почти все ишью кажутся разумными (за исключением ишью про байнды, там пока не уверена, что со всем согласна, скорее всего будут вопросы), поэтому спорить не буду :). 
Тогда начинаю править, спасибо.

**Comment by KateBu** [comment]
добавила алиасы для типов данных внутри конфига и окружения. Остальные типы (за исключением единичных употреблений) уже обернуты в newtype или data

**Comment by DonDokidon** [comment]
https://github.com/KateBu/bot-1.3/blob/ca9428a3e48e6902fcbaf06c839616d5b335ae1b/src/API/Telegram/Cleaners/MakeMbParams.hs#L6-L8
Думаю тут тоже стоило бы указать, что первый текст это ключ (в самой структуре тоже). А еще у тебя все еще существует 2 модуля Messages с разным содержимым :)

**Comment by KateBu** [comment]
сделала отдельную папку для текстовых сообщений из проекта и все сообщения отправила туда, переименовав модули. Ну и Key добавила

**Comment by KateBu** [comment]
Однако у меня в разных папках модули с одинаковыми названиями, типа Structs, Internals, Data etc. Это норм или надо переименовывать?

**Comment by DonDokidon** [comment]
Суть не в том, что у тебя есть модули с одинаковыми названиями, суть в том что у тебя их назначения различались при одном названии. В случае Struct у тебя там хранится тип, это норм. В  Something.Thing.Internals должны храниться основные функции по работе с чем-то и напрямую обычно Internals не импортируется (импортируется косвенно через Something.Thing вместе с другими нужными штуками вроде тех же Types), не знаю насколько это у тебя выполняется. В случае с Messages, в одном модуле у тебя хранились текстовые сообщения, а в другом типы аля MessageType.

**Comment by KateBu** [comment]
ок, поняла
