### ISSUE TITLE
Именования переменных не всегда понятны

### ISSUE THREAD

**Issue by DonDokidon** [KateBu/bot-1.3#7]
https://github.com/KateBu/bot-1.3/blob/04be57027cfa47804428e1bd90c163b4fcb8b70b/src/Environment/InitEnvironment/SetBotSettings.hs#L56

 В некоторых функциях твои переменные сокращаются до 2-1 буквы. В этих случаях совершенно не ясно что это и для чего. В примере приходится лезть в объявление `LongPollResponse`, чтобы понять что есть что. Не бойся давать длинные имена переменным, стремись сделать код понятным, а не кратким. А переменные из одной буквы можешь оставить лямбдам и кейсам (и то в самых тривиальных случаях).

**Comment by KateBu** [comment]
просмотрела проект на наличие непонятных имен переменных, все исправила
