### ISSUE TITLE
Именования модулей

### ISSUE THREAD

**Issue by DonDokidon** [KateBu/bot-1.3#8]
https://github.com/KateBu/bot-1.3/blob/04be57027cfa47804428e1bd90c163b4fcb8b70b/src/Environment/Environment.hs#L1

Такого  быть не должно. Назови его Main, Internals или еще что-то по смыслу придумай, или вообще вынеси его  (чтобы было просто `module Environment` ). В общем подобных повторений быть не должно. `module Config.ConfigData` тоже не лучший вариант, почему не просто `module Config.Data` ? А еще у тебя есть 2 модуля с именем `InitEnvironment` и они оба имеют какие-то функции, что очень странно. В функции я не вчитывался, но либо эти функции логически принадлежат одному модулю (значит нужно объединить), либо название какого-то не отражает суть.

**Comment by KateBu** [comment]
может ли совпадать название модуля и папка, из которой импортируются функции? типа модуль Wrapper.hs импортирует функции из модулей папки Wrapper ?

**Comment by evgeny-osipenko** [comment]
Если ты об этом, то да, можно:
```hs
-- Domain/Group.hs
module Domain.Group
    ( Foo(..)
    , Bar(BarX, BarY)
    , makeDucks
    ) where

import qualified Domain.Group.Ducks as Ducks
import Domain.Group.Foobar

makeDucks = Ducks.make Ducks.Quackable defaultDuckCount

defaultDuckCount = 15
```
```hs
-- Domain/Group/Ducks.hs
module Domain.Group.Ducks where

import Domain.Group.Ducks

make category count = ...
```
```hs
-- Domain/Group/Foobar.hs
module Domain.Group.Foobar where

data Foo = Foo Int
data Bar = BarX Foo Bar | BarY
```

**Comment by KateBu** [comment]
да, об этом, спасибо

**Comment by KateBu** [comment]
переименовала
